import { useRouter } from 'next/router'
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs'
import { SessionContextProvider } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import Layout from '../components/Layout.js'

export default function Contact() {
  const user = null
  const onClickLogout = async () => {
    
    const { error } = await supabase.auth.signOut()
    router.push('/index')
  }
  return (
    <Layout>
      <Head>
        <title>WebTech - user signedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        className="rounded px-3 py-2 text-white bg-slate-500 hover:bg-blue-500"
        onClick={onClickLogout}
      >
        logout
      </button>
      <pre><code>{JSON.stringify(user, null, 2)}</code></pre>
    </Layout>
  )
}
