import { useRouter } from "next/router";
import { useContext, useEffect } from "react";
import Head from "next/head";
import Layout from "../components/Layout.js";
import UserContext from "../components/UserContext";
import UserImage from "../components/UserImage";

export default function Contact() {
  const { user, logout, loading } = useContext(UserContext);
  const router = useRouter();
  var json;
  useEffect(() => {
    if (!(user || loading)) {
      router.push("/login");
    }
  }, [user, loading, router]);
  const onClickLogout = function () {
    logout();
  };
  return (
    <Layout>
      <Head>
        <title>WebTech - user signedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!(user || loading) ? (
        <p>Redirecting...</p>
      ) : (
        <>
          <div class="flex flex-row">
            {" "}
            <div class="basis-1/4">
              {" "}
              <UserImage className="rounded-full w-32 border-4 bg-white" />
            </div>{" "}
            <div className="grid place-items-center">
              <p className="font-bold text-3xl">
                {user.user_metadata.preferred_username}
                <br></br>
                {user.email}
              </p>
            </div>
          </div>

          <button
            className="rounded px-3 py-2 text-white bg-slate-500 hover:bg-blue-500"
            onClick={onClickLogout}
          >
            Logout
          </button>

          <pre>
            <code>{JSON.stringify(user, null, 2)}</code>
          </pre>
        </>
      )}
    </Layout>
  );
}
