import { useState, useContext } from "react";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Head from "next/head";
import UserContext from "../components/UserContext";
import Layout from "../components/Layout.js";

export default function Contact() {
  const { user, logout, loading } = useContext(UserContext);
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const onSubmit = async function (e) {
    e.preventDefault();
    const data = new FormData(e.target);
    let obj = Object.fromEntries(data);
    user ? ((obj.id = user.id), (obj.author = user.email)) : <></>;
    console.log(obj);
    const { error } = await supabase
      .from("articles")
      .insert(obj, { returning: "minimal" });

    if (error) {
      console.log(error);
      if (error.code == "42501") {
        setMessage("You must be connected to write an article");
      } else {
        setMessage("Sorry, an unexpected error occured.");
      }
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Thank you for contacting us. We will get back to you promptly.</p>
        </div>
      );
    }
  };
  return (
    <Layout>
      <Head>
        <title>WebTech - send articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="wt-title">Send an article</h1>
      <form className="[&_span]:block grid gap-3" onSubmit={onSubmit}>
        <div>
          <label>
            <span>Title</span>
            <input type="text" name="title" />
          </label>
        </div>
        <div>
          {/* <label>
            <span>Content</span>
            <input type="text" name="content" className="h-40" />
          </label> */}

          <label
            for="content"
            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            Your message
          </label>
          <textarea
            id="content"
            name="content"
            rows="4"
            class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Write your thoughts here..."
          ></textarea>
        </div>
        <div>
          <label>
            <span>First categories</span>
            <input type="text" name="categorie1" />
          </label>
        </div>
        <div>
          <label>
            <span>Second categories</span>
            <input type="text" name="categorie2" />
          </label>
        </div>

        <div>
          <button className="rounded py-1 px-3 text-white bg-slate-500 hover:bg-blue-500">
            Send
          </button>
        </div>
      </form>
      {message && (
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      )}
    </Layout>
  );
}
