import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout.js'
import React, { useState } from 'react';

export default function Counter() {
    const[count, setCount]=useState(0);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Counter
      </h1>
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" onClick={() => setCount(count + 1)}>
    Click me
  </button>
  
      <p>You clicked {count} times</p>
   
    </Layout>
  )
}
